### PR TITLE
Harmonise profile defaults with openaps/oref0

### LINKED ISSUE #27: Several oref0 profile defaults diverge from openaps/oref0
**Describe the bug**
Several oref0 profile defaults diverge from openaps/oref0 

One example is the default value for max_iob in profile/index.js#L11 is set to 9, and should be zero.

Please note this has no effect in Trio since it is not set identically in Trio defaults, but it should be cleaned up:

https://github.com/nightscout/trio-oref/blob/d1dfb7099d59e4f7779e5fc5c75f8ca299d91ef2/lib/profile/index.js#L11

    max_iob: 9 // if max_iob is not provided, will default to zero

The openaps/oref0 default is zero:

    max_iob: 0 // if max_iob is not provided, will default to zero 

**Expected behavior**
Our code base should match orenaps/oref0 unless there are good reasons not to. In this case, there is no reason to divert from orenaps/oref0.

### PR DESCRIPTION
**Pull request by bjornoleh**
This PR adresses observations made in #27, where several oref0 profile defaults were found to diverge from openaps/oref0.

Harmonised with openaps/oref0:

max_iob: 0 // if max_iob is not provided, will default to zero
    , max_daily_safety_multiplier: 3
    , current_basal_safety_multiplier: 4
    , autosens_max: 1.2
    , autosens_min: 0.7

    , enableSMB_with_COB: false // enable supermicrobolus while COB is positive
    , enableSMB_with_temptarget: false // enable supermicrobolus for eating soon temp targets

    , allowSMB_with_high_temptarget: false // allow supermicrobolus (if otherwise enabled) even with high temp targets
    , maxSMBBasalMinutes: 30 // maximum minutes of basal that can be delivered as a single SMB with uncovered COB
    , maxUAMSMBBasalMinutes: 30 // maximum minutes of basal that can be delivered as a single SMB when IOB exceeds COB

    , bolus_increment: 0.1 // minimum bolus that can be delivered as an SMB

    , insulinPeakTime: 75 // number of minutes after a bolus activity peaks.  defaults to 55m for Fiasp if useCustomPeakTime: false

Moving these lines to harmonise the relative position in the file:

    , enableSMB_high_bg: false // enable SMBs when a high BG is detected, based on the high BG target (adjusted or profile)
    , enableSMB_high_bg_target: 110 // set the value enableSMB_high_bg will compare against to enable SMB. If BG > than this value, SMBs should enable.

Will keep these defaults different from openaps/oref0:

    ,sensitivity_raises_target: false ( openaps/oref0 = `true`
)

These settings still exist in openaps/oref0, but are not included in trio-oref, as they are obsolete and/or only relevant for rig setups, and not relevant for Trio:

    ,bolussnooze_dia_divisor: 2

    , edison_battery_shutdown_voltage: 3050
    , pi_battery_shutdown_percent: 2

Other profile variables related to dynamic ISF and `smb_delivery_ratio` which diverge from openaps/oref0 are kept:

    , smb_delivery_ratio: 0.5 //Default value: 0.5 Used if flexible delivery ratio is not used. This is another key OpenAPS safety cap, and specifies what share of the total insulin required can be delivered as SMB. This is to prevent people from getting into dangerous territory by setting SMB requests from the caregivers phone at the same time. Increase this experimental value slowly and with caution.
    , adjustmentFactor: 0.8
    , adjustmentFactorSigmoid: 0.5
    , useNewFormula: false
    , enableDynamicCR: false
    , sigmoid: false
    , weightPercentage: 0.65 
    , tddAdjBasal: false // Enable adjustment of basal based on the ratio of 24 h : 10 day average TDD
    , threshold_setting: 60 // Use a configurable threshold setting

Removed this redundant comment:
     // autoISF variables
     
Edit:
Changing `enableUAM` from `true` to `false`, to match the currently used defaults in Trio (defaults to `true` in openaps/oref0 since 2017)

### CODE REVIEW

File: lib/profile/index.js [hunk 1]
```diff
@@ -8,11 +8,11 @@ var _ = require('lodash');
 
 function defaults ( ) {
   return /* profile */ {
-    max_iob: 9 // if max_iob is not provided, will default to zero
-    , max_daily_safety_multiplier: 5
-    , current_basal_safety_multiplier: 6
-    , autosens_max: 2.5
-    , autosens_min: 0.5
+    max_iob: 0 // if max_iob is not provided, will default to zero
```
Comment (MikePlante1) [inline lib/profile/index.js]: extra space accidentally added to end

File: lib/profile/index.js [hunk 2]
```diff
@@ -34,8 +34,8 @@ function defaults ( ) {
     // WARNING: use SMB with caution: it can and will automatically bolus up to max_iob worth of extra insulin
     , enableUAM: true // enable detection of unannounced meal carb absorption
```
Comment (MikePlante1) [inline lib/profile/index.js]: `enableUAM` is defaulted to `false` in Trio, so maybe it's worth updating that in this PR as well.

**Review by MikePlante1 — DISMISSED** [review]
Code review looks good. I added a couple comments if you want to address them, otherwise LGTM. I tested in a simulator.

File: lib/profile/index.js (hunk 2 above)
Comment (bjornoleh) [reply lib/profile/index.js]: Thanks for your review, the changes has been made.

Comment (bjornoleh) [reply lib/profile/index.js]: Actually, seeing that UAM has been on by default in openaps/oref0 since 2017, we might want to reconsider setting `enableUAM` to `false`. But in that case perhaps we should consider changing this in Trio defaults as well.

This is not an important matter for me though, and we can keep it as is too.

Comment (MikePlante1) [reply lib/profile/index.js]: I agree that UAM should be enabled by default. Not sure if that’d cause everyone’s settings to get reset again or not, though. I think there’s a way to do it without causing a reset, but the code wouldn’t be as clean. Maybe when settings are moved out of json it’ll be easier to update defaults?

**Review by MikePlante1 — APPROVED** [review]

File: lib/profile/index.js
Comment (mountrcg) [inline lib/profile/index.js:1]: This looks good and sensible to me. Funny enough I looked yesterday through the same file and wondered about some setting but basically said to myself not to worry as these are set by using the defaults set in Trio. But sensible to keep it inline! Especially bolus_increment. Good stuff - reviewed and thumbs up.

**Review by mountrcg — APPROVED** [review]
